/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IconsFontawesome {}
  interface IconsMaterial {}
  interface IconsUiFabric {}
}

declare global {


  interface HTMLIconsFontawesomeElement extends Components.IconsFontawesome, HTMLStencilElement {}
  var HTMLIconsFontawesomeElement: {
    prototype: HTMLIconsFontawesomeElement;
    new (): HTMLIconsFontawesomeElement;
  };

  interface HTMLIconsMaterialElement extends Components.IconsMaterial, HTMLStencilElement {}
  var HTMLIconsMaterialElement: {
    prototype: HTMLIconsMaterialElement;
    new (): HTMLIconsMaterialElement;
  };

  interface HTMLIconsUiFabricElement extends Components.IconsUiFabric, HTMLStencilElement {}
  var HTMLIconsUiFabricElement: {
    prototype: HTMLIconsUiFabricElement;
    new (): HTMLIconsUiFabricElement;
  };
  interface HTMLElementTagNameMap {
    'icons-fontawesome': HTMLIconsFontawesomeElement;
    'icons-material': HTMLIconsMaterialElement;
    'icons-ui-fabric': HTMLIconsUiFabricElement;
  }
}

declare namespace LocalJSX {
  interface IconsFontawesome {}
  interface IconsMaterial {}
  interface IconsUiFabric {}

  interface IntrinsicElements {
    'icons-fontawesome': IconsFontawesome;
    'icons-material': IconsMaterial;
    'icons-ui-fabric': IconsUiFabric;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'icons-fontawesome': LocalJSX.IconsFontawesome & JSXBase.HTMLAttributes<HTMLIconsFontawesomeElement>;
      'icons-material': LocalJSX.IconsMaterial & JSXBase.HTMLAttributes<HTMLIconsMaterialElement>;
      'icons-ui-fabric': LocalJSX.IconsUiFabric & JSXBase.HTMLAttributes<HTMLIconsUiFabricElement>;
    }
  }
}


